version: '3.4'  # Use version 3.4 or higher for platform specification

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "testTopic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis/redis-stack:latest
    volumes:
      - ./redis-data:/data/
    ports:
      - "6379:6379"
      - "8001:8001"