version: '3.4'  # Use version 3.4 or higher for platform specification

services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "testTopic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cmak:
    image: hlebalbau/kafka-manager:latest
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "host.docker.internal:2181"

  redis:
    image: redis/redis-stack:latest
    volumes:
      - ./redis-data:/data/
    ports:
      - "6379:6379"
      - "8001:8001"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'e-commerce'          # The name of the database to create
      MYSQL_USER: 'appuser'                    # The MySQL user
      MYSQL_PASSWORD: 'appuserpassword'           # The MySQL password application user
      MYSQL_ROOT_PASSWORD: 'commerce'   # The password for the root user
    ports:
      - "3307:3306"
    volumes:
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

volumes:
  mysql_data:
  zookeeper_data:
  zookeeper_datalog: